### ISSUE TITLE
filter_by_feature.R: An error occurred: object 'sf_indices' not found

### ISSUE THREAD

**Issue by hasruleng** [wwf-ff/ForestForesight#17]
**Describe the bug**
when running filter_by_feature and length(filtercolumn) is 0
then it will enter this if statement
`        ff_cat("The feature", fltr_features[i], "was not found, skipping filtering for this feature\n", color = "yellow")
`for example:
The feature initialforestcover was not found, skipping filtering for this feature

this will skip initialization of sf_indices in the else statement

**To Reproduce**

1. when the runtime is trying to access sf_indices
```
      if (length(sfa_indices) == 0) {
        sfa_indices <- c(sfa_indices, sf_indices)
      } else {
        sfa_indices <- intersect(sfa_indices, sf_indices)
      }
```
2. Observe 
An error occurred: object 'sf_indices' not found

**Expected behavior**
Change of logic/better handling, so there will be No error

**Comment by ZillahCalle** [comment]
Thanks for bringing this up! The bug is now fixed.
