### ISSUE TITLE
Cannot use tile as identifier in ff_sync

### ISSUE THREAD

**Issue by hasruleng** [wwf-ff/ForestForesight#9]
**Describe the bug**
ff_sync should be able to take tile, country, or SpatVector for its "identifier" parameter
**To Reproduce**
#1. run this script:
identifier <- "00N_080W"  # does this work?
#identifier <- shape # use this if you want to download the area that you click from "Loading Area of Intereset"

# Call the ff_sync function
ff_sync(
  ff_folder = download_folder,
  identifier = identifier,
  download_model = TRUE, #prediction models
  download_data = TRUE, #pre-processed data
  download_predictions = FALSE, #disable this if you don't want to download previous prediction
  verbose = TRUE
)
#2. You will get
Error in ff_sync(ff_folder = download_folder, identifier = identifier,  : 
  Invalid country code

**Expected behavior**
It should download a tile given as identifier

**Comment by ZillahCalle** [comment]
Thanks for pointing that out! There was a small error in ff_sync, but it's fixed now!
